In [2]:
import numpy as np
import wilson, flavio, smelli
import wc_defs

In [16]:
gzp = 0.5
mzp = 1000
alpha = gzp**2 / mzp**2
theta_23 = 0.1

In [19]:
import wilson
from wilson import wcxf

In [13]:
wcs = wilson.Wilson(wc_defs.calcinputlist(alpha, theta_23, sphi=0), scale = 1000, eft = 'SMEFT', basis = 'Warsaw')

lam11 =  -0.0


TypeError: Wilson.__init__() got an unexpected keyword argument 'par'

In [12]:
print(flavio.default_parameters

In [9]:
flavio.sm_prediction('BR(Bs->mumu)')

3.6289314570849374e-09

In [17]:
flavio.np_prediction('BR(Bs->mumu)',wcs)

1.615276159996604e-08

In [26]:
print(wc_defs.calcinputlist(alpha, theta_23, sphi=0))

lam11 =  -0.0
{'ll_2222': -3.125e-08, 'lq1_2211': (9.700670386212371e-12+0j), 'lq1_2212': (-8.658907477034433e-11+0j), 'lq1_2213': (8.843657856535255e-10+0j), 'lq1_2222': (1.9820793986803192e-10+0j), 'lq1_2223': (-4.0436996125312195e-09+0j), 'lq1_2233': (2.0625424723079083e-08+0j), 'ee_3333': -1.25e-07, 'uu_3333': -5.555555555555555e-08, 'dd_3333': -1.3888888888888887e-08, 'eu_3333': 1.6666666666666665e-07, 'ed_3333': -8.333333333333333e-08, 'ud1_3333': 5.555555555555555e-08, 'le_2233': -1.25e-07, 'lu_2233': 8.333333333333333e-08, 'ld_2233': -4.166666666666666e-08, 'qe_1133': (1.9401340772424743e-11+0j), 'qe_1233': (-1.7317814954068865e-10+0j), 'qe_1333': (1.768731571307051e-09+0j), 'qe_2233': (3.9641587973606384e-10+0j), 'qe_2333': (-8.087399225062439e-09+0j), 'qe_3333': (4.1250849446158165e-08+0j), 'qu1_1133': (-1.2934227181616496e-11+0j), 'qu1_1233': (1.1545209969379243e-10-0j), 'qu1_1333': (-1.1791543808713672e-09+0j), 'qu1_2233': (-2.642772531573759e-10+0j), 'qu1_2333': (5.3915994

In [44]:
import wcxf
#wcxf_smeft = wcxf.WC(eft='SMEFT', basis='Warsaw', scale=1000,
                  # values=wc_defs.calcinputlist(alpha, theta_23, sphi=0))
wc_flavio = flavio.WilsonCoefficients()
wc_flavio.set_initial(wc_defs.calcinputlist(alpha, theta_23, sphi=0), scale = 1000, eft='SMEFT', basis='Warsaw up')
wc_dict = wc_flavio.get_wcxf(sector='dB=dL=0', scale=1000, par = flavio.default_parameters, eft='SMEFT', basis='Warsaw up').dict

lam11 =  -0.0


In [46]:
C = wilson.util.smeftutil.wcxf2arrays_symmetrized(wc_dict)

In [47]:
print(C)

{'ll': array([[[[ 0.000e+00+0.j,  0.000e+00+0.j,  0.000e+00+0.j],
         [ 0.000e+00-0.j,  0.000e+00+0.j,  0.000e+00+0.j],
         [ 0.000e+00-0.j,  0.000e+00-0.j,  0.000e+00+0.j]],

        [[ 0.000e+00+0.j,  0.000e+00+0.j,  0.000e+00+0.j],
         [ 0.000e+00+0.j,  0.000e+00+0.j,  0.000e+00+0.j],
         [ 0.000e+00+0.j,  0.000e+00+0.j,  0.000e+00+0.j]],

        [[ 0.000e+00+0.j,  0.000e+00+0.j,  0.000e+00+0.j],
         [ 0.000e+00-0.j,  0.000e+00+0.j,  0.000e+00+0.j],
         [ 0.000e+00+0.j,  0.000e+00+0.j,  0.000e+00+0.j]]],


       [[[ 0.000e+00-0.j,  0.000e+00+0.j,  0.000e+00-0.j],
         [ 0.000e+00-0.j,  0.000e+00-0.j,  0.000e+00-0.j],
         [ 0.000e+00-0.j,  0.000e+00-0.j,  0.000e+00-0.j]],

        [[ 0.000e+00+0.j,  0.000e+00+0.j,  0.000e+00+0.j],
         [ 0.000e+00-0.j, -3.125e-08+0.j,  0.000e+00+0.j],
         [ 0.000e+00-0.j,  0.000e+00-0.j,  0.000e+00+0.j]],

        [[ 0.000e+00+0.j,  0.000e+00+0.j,  0.000e+00+0.j],
         [ 0.000e+00-0.j,  0.000e+00+

In [42]:
from flavio.physics import ckm as ckm_flavio
ckm = ckm_flavio.get_ckm(flavio.default_parameters)

TypeError: 'ParameterConstraints' object is not subscriptable

In [40]:
print(flavio.default_parameters.read_default())

None


In [8]:
print(wc_flavio)

In [23]:
from numpy import pi, sqrt
import numpy as np
#from flavio.config import config


def sigma_llqq_tot(sh,l,q1,q2,wc_eff):
    r"""Total cross section of e^+ e^- \to q1 q2

    Returns $\sigma$ in units of GeV$^{-2}$

    Parameters:
    - `sh`: centre of mass energy in GeV$^2$ of the lepton pair
    - `l`: lepton flavour, should be 'e'
    - `q1`, `q2`: outgoing quark flavours
    - `wc_eff`: SM + SMEFT amplitude for the process as dictionary with entries corresponding to different Wilson coefficients
    """

    # this function returns the piece coming out of the integration of the Dirac traces
    def sh_func(sh, coefficient):
        return coefficient * sh**3

    # Define a dictionary of the non-zero Dirac traces when integrating over the full phase space
    f_fully_integrated = {}
    f_fully_integrated['SSLL'] = f_fully_integrated['SSLR'] = f_fully_integrated['SSRL'] = f_fully_integrated['SSRR'] = lambda sh: sh_func(sh, 1/4)
    f_fully_integrated['VVLL'] = f_fully_integrated['VVLR'] = f_fully_integrated['VVRL'] = f_fully_integrated['VVRR'] = lambda sh: sh_func(sh, 1/3)
    f_fully_integrated['TTLR'] = f_fully_integrated['TTRL'] = lambda sh: sh_func(sh, 4/3)

    # Calculate the cross-section sigma
    sigma = 0
    for gamma in 'SVT':
        for gammap in 'SVT':
            for X in 'LR':
                for Y in 'LR':
                    key = '{}{}{}{}'.format(gamma, gammap, X, Y)
                    if key in f_fully_integrated:
                        sigma += 3 / (16 * pi * sh**2) * f_fully_integrated['{}{}{}{}'.format(gamma, gammap, X, Y)](sh) #* wc_eff['C{}{}{}_e{}'.format(gamma,X,Y,q1)][0,0,q1,q2] * np.conjugate(wc_eff['C{}{}{}_e{}'.format(gammap,X,Y,q1)][0,0,q1,q2])

    # Return total cross-section
    return sigma


In [27]:
for sh in [0.01, 10, 50, 100, 150, 200, 240, 300, 365]:
    print(sigma_llqq_tot(sh,1,1,3,4))

0.0029841551829730383
2.9841551829730375
14.920775914865189
29.841551829730378
44.76232774459556
59.683103659460755
71.61972439135292
89.52465548919112
108.92166417851587


In [10]:
print(np.zeros((3,3,3,3)))

[[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]


 [[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]


 [[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]]


In [49]:
dict = {'a':1, 'b':2, 'c':3}
def fun_fun(x):
    sigma = 0
    for key in dict.keys():
        sigma += dict[key] * x
    return sigma
fun_fun(5)

30

In [50]:
def function_1(sh, q):
    _dict = {q: sh}
    return _dict


def function_2(a):
    _dict = function_1(240, 'u')
    for key in _dict:
        print(key, a * _dict[key])
    return
function_2(3)

u 720
